user.name = "Piotr Kalinowski"
user.email = "pitkali@gmail.com"
merge-tools.vimdiff.program = "nvim"

[working-copy]
eol-conversion = "input"

[revset-aliases]
"immutable_heads()" = "builtin_immutable_heads() | remote_bookmarks()"
'closest_pushable(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'

[ui]
default-command = "log"
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@ & bookmarks())", "--to", "closest_pushable(@)"]
ll = ["log", "-r", "ancestors(@, 10)"]

